### ISSUE TITLE
Support for NSFW materials

### ISSUE THREAD

**Issue by MediaMoots** [FlailingFog/KK-Blender-Shader-Pack#7]
Hello.

It would be great if there was a way to add nipples/genitals to the body shader. 

Nipples have some support in V3 but it's not easy to scale them. 
As for the genitals, they have a material based on this template https://github.com/DeathWeasel1337/KK_Plugins/blob/master/src/UncensorSelector.Core/Template.xml

By the way, what is "[Grey's Mesh Exporter](https://github.com/FlailingFog/KK-Blender-Shader-Pack/blob/63c40d8a8abd8494ef36a70b48aba929e3b6e63b/Plugin/importTextures.py#L3)"? 
Thanks.

**Comment by MediaMoots** [comment]
Update:
It appears that the genitals are applied from the material `cf_body_00_t`
Attached is a sample of that texture.

[cf_body_00_t-DXT5.zip](https://github.com/FlailingFog/KK-Blender-Shader-Pack/files/6189593/cf_body_00_t-DXT5.zip)

**Comment by MediaMoots** [comment]
![image](https://user-images.githubusercontent.com/81146974/112153041-daef7b00-8c1d-11eb-99df-ed8e9a773f9d.png)
Got it partially working with the above nodes, but the shading is not correct.

**Comment by FlailingFog** [comment]
I admit the mapping portion is wonky. At the moment scale and location seem like they're linked so I need to see if there's some way to unlink them.

The texture you attached has a white background so multiplication could be used to apply it to the skin color
![image](https://user-images.githubusercontent.com/65811931/112239688-50a71700-8c1d-11eb-9a9d-a629d4838bd1.png)
Thanks for showing this, if all of them are like this I can add an easy way to use it in the V4 version of the shader

Since you asked, Grey's Mesh Exporter is a very useful plugin by Grey on the Illusion soft discord. It exports textures like material editor does, but it exports all of them at once and it exports them with consistent naming, so instead of manually exporting each texture and manually loading each texture into the material templates, it can all be done automatically (with a 90% success rate). I plan on utilizing it in the V4 version of the script/shader pack.

**Comment by MediaMoots** [comment]
@FlailingFog 
Very cool, thank you.
I'll check the exporter out.

> I admit the mapping portion is wonky. At the moment scale and location seem like they're linked so I need to see if there's some way to unlink them.

Maybe the texture would need to be positioned individually, I tried that, and it is hard to get the positions right.

> The texture you attached has a white background so multiplication could be used to apply it to the skin color
To think it was that easy XD
Of course, the hue is not right, but it's a step in the right direction, thanks.

**Comment by MediaMoots** [comment]
Alright, got the hue working
![image](https://user-images.githubusercontent.com/81146974/112250969-50e2f900-8c95-11eb-9c9f-a9d02a711114.png)
There's probably a better way to do this though XD

**Comment by FlailingFog** [comment]
In [V4.1.2](https://github.com/FlailingFog/KK-Blender-Shader-Pack/releases/tag/V4.1.1), I put a spot for loading these body_00_t textures into the NSFW texture group in the Body material, plus some sliders to adjust the hue 
I also added an easier way to scale things (including nipples)

**Comment by MediaMoots** [comment]
@FlailingFog 
Hi, great update, works flawlessly.

Is there a way to add pubic hair?
Thanks.

**Comment by FlailingFog** [comment]
You can probably just do something [similar to this](https://github.com/FlailingFog/KK-Blender-Shader-Pack/wiki/Adding-and-Positioning-Facepaint-Makeup).

**Comment by MediaMoots** [comment]
Yup, thanks
